version: '3.8'

services:
  db:
    image: postgis/postgis:latest
    container_name: postgres_db
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: geodb
    ports:
      - "5432:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql 
    networks:
      - app_network


  fastapi_backend:
    build: ./backend
    container_name: fastapi_backend
    volumes:
      - ./server.log:/server.log 
    depends_on:
      - db
    ports:
      - "8000:8000"
    networks:
      - app_network

networks:
  app_network:
    driver: bridge

    